### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by pbrisbin** [supki/envparse#12]
:wave: Hello again,

I opened a few Issues and Pull Requests, but haven't gotten any comments in over a month. At this point, my team went ahead and made a project-local clean-room implementation of this library to use instead. It's quite a bit simpler, with minimal loss of functionality, but uses (mostly) the same interface.

I'm wondering if you'd be open to handing off maintainer-ship of this Hackage package, so we could replace it with our implementation.

If I get no response we'll probably release under a different name, but I'd be sad to fragment the space with two incredibly similar packages (from a usage standpoint).

**Comment by andrewthad** [comment]
This should be raised on the mailing lists for library maintainership. Also, this library doesn't build with GHC 8.4 because of missing Semigroup instances.
