### ISSUE TITLE
Wider var docs output

### ISSUE THREAD

**Issue by arnauorriols** [supki/envparse#14]
Is it possible to configure envparse to output the docs of the variables in wider rows? The current 30 columns output is by far too narrow for my needs.

If not currently possible, would you be open to PR implementing such feature? I'm willing to implement it if given some design guidelines.

**Comment by supki** [comment]
It's not possible to customize help text formatting in any way right now. The formatter is generally pretty hacky (to avoid the dependency on a pretty-printer library), but it shouldn't be too hard to add a field to the `Info` type with the number of columns a help line should try to fit in (80 is probably a reasonable default here); then the variable description's length can be calculated from that hint. I think it would be a useful addition to the library.

**Comment by arnauorriols** [comment]
ping

**Comment by arnauorriols** [comment]
ping

**Comment by arnauorriols** [comment]
ping

**Comment by arnauorriols** [comment]
ping
