### ISSUE TITLE
Upload new version to hackage

### ISSUE THREAD

**Issue by shinzui** [supki/envparse#20]
I just got bitten by #9 and had to point to master to fix my issue. Could you please upload a new version?

**Comment by NorfairKing** [comment]
Ping to the maintainer

**Comment by NorfairKing** [comment]
Ping again^ @Kleidukos
Is there a way to suggest taking over maintainership?

**Comment by Kleidukos** [comment]
@NorfairKing Same way as always: https://wiki.haskell.org/Taking_over_a_package

**Comment by NorfairKing** [comment]
@supki Would you be up for sharing maintenance?

**Comment by pbrisbin** [comment]
:wave: Hi there, it's been so long that I completely forgot that I motivated the switch from `keep` to `sensitive`!

For what it's worth, I just implemented a workaround in `$WORK_PROJECT`:

```hs
kept :: Parser e a -> Parser e a
kept = Parser . hoistAlt (\v -> v { varfKeep = True }) . unParser
```

This lets you decide from the outside to remove this behavior:

```diff
- parse id $ (,)
+ parse id $ kept $ (,)
    <$> var str "FOO" mempty
    <*> var str "BAR" mempty
```

I even re-opened my fork and started to implement it here to PR and was super confused when `varfKeep` didn't exist :facepalm: 

Anyway, this radio silence could be enough to formally go with the override procedure,

> 1. Try to contact the maintainer. Give him/her reasonable time to respond.
> 2. State your intention to take over the package in a public forum (we recommend the haskell-cafe and/or libraries list). CC the maintainer.
> 3. Wait a while.
> 4. Send an email to the hackage administrators ([hackage-admin@haskell.org](mailto:hackage-admin@haskell.org)), with a link to the public email thread.
> 5.  The admins will grant you maintenance rights or upload a patched version for you.

An argument could be made that we're already at (4), but we could also start at step (2) with a haskell-cafe email.

@NorfairKing are you interested in proceeding on this, or (if you no one objects), I can.

**Comment by supki** [comment]
Hey, very sorry for completely forgetting about this project even existing. (We don't use Hackage as $WORK so we weren't really hit by the lack of maintenance). I'll make a release later today once I get to my PC.

I'm open to sharing the maintenance btw, hopefully there isn't too much work anyway.

**Comment by pbrisbin** [comment]
Awesome, thanks!

That should close #12 and #18, along with this Issue. :+1:

**Comment by tchoutri** [comment]
Awesome!!
