### ISSUE TITLE
Hackage release of 0.2.2?

### ISSUE THREAD

**Issue by olorin** [supki/envparse#3]
Hi,

Just wondering if you had any plans to do a Hackage release of 0.2.2? The exposed `helpDoc` makes the package fit my usecase a lot better (combining `envparse` and `optparse-applicative` in one program).

Thanks!

**Comment by supki** [comment]
I was going to merge #2 before I cut off the release, but I don't see why I can't release now if the addition of `helpDoc` is helpful.

On [hackage](https://hackage.haskell.org/package/envparse-0.2.2).

**Comment by olorin** [comment]
Thanks, appreciated. :+1:
